---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Multi instance example
Parameters:
  Environment:
    Type: String
    Description: Name of the environment
    AllowedValues:
    - dev
    - stage
    - prod
  InstanceType:
    Type: String
    Description: Instace type to use
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
  KeyName:
    Type: String
    Description: SSH key to use
  ImageId:
    Type: String
    Description: AMI to use
    Default: ami-785db401
Resources:
  Ec2Instance01:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: Instance01
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt update
          apt -y install nginx
  Ec2Instance02:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: instance02
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt update
          apt -y install nginx
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 192.168.50.10/32
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
