AWSTemplateFormatVersion: '2010-09-09'
Description: AWS read replicate template
Parameters:
  AutoMinorVersionUpgrade:
    AllowedValues:
    - 'true'
    - 'false'
    Default: true
    Type: String
  DBInstanceClass:
    Default: db.m4.large
    Description: Database instance class
    Type: String
  DBInstanceIdentifier:
    Description: Name of the new read replica. If not set you you will get a random
      endpoint.
    Type: String
  DiskIops:
    Default: '2000'
    Description: Disk Iops set to 0 to disable
    Type: String
  DiskSize:
    Default: '100'
    Description: Disk size in GB. Must be 100G with provisioned IOPS
    Type: String
  Environment:
    AllowedValues:
    - dev
    - stage
    - prod
    Description: Name of environment to deploy to
    Type: String
  PubliclyAccessible:
    AllowedValues:
    - 'false'
    - 'true'
    Default: 'false'
    Type: String
  SourceDBInstanceIdentifier:
    Description: Create new read replica from this source db instance identifier.
    Type: String
  StorageEncryption:
    AllowedValues:
    - 'true'
    - 'false'
    Default: true
    Type: String
  StorageType:
    AllowedValues:
    - io1
    - gp2
    Default: io1
    Type: String
Resources:
  ReplicaDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DiskSize
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod: '0'
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      Engine: mysql
      EngineVersion: 5.7.19
      Iops: !Ref DiskIops
      PubliclyAccessible: !Ref PubliclyAccessible
      SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifier
      StorageEncrypted: !Ref StorageEncryption
      StorageType: !Ref StorageType
      Tags:
      - Key: Name
        Value: Read Replica Database
